version: '3'
services:
  #  2 -> 3: change 2.14.0 tags to 3.0.0

  dsw-server:
    image: datastewardshipwizard/wizard-server:2.14.0
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - rabbitmq
      # 2 -> 3:
      # - postgres
      # - minio
    volumes:
      - ./conf2/server.yml:/application/engine-wizard/config/application.yml:ro
      # 2 -> 3:
      # - ./conf3/dsw.yml:/application/engine-wizard/config/application.yml:ro

  dsw-client:
    image: datastewardshipwizard/wizard-client:2.14.0
    restart: always
    ports:
      - 8080:80
    environment:
      API_URL: http://localhost:3000

  docworker:
    image: datastewardshipwizard/document-worker:2.14.0
    restart: always
    depends_on:
      - postgres
      - minio
    volumes:
      - ./conf2/docworker.yml:/app/config.yml:ro
      # 2 -> 3:
      # - ./conf3/dsw.yml:/app/config.yml:ro

  # NEW (newly used for DSW 3)
  postgres:
    image: postgres:13.2
    restart: always
    ports:
      - 127.0.0.1:15432:5432
    environment:
      POSTGRES_DB: wizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # (!) Mount for persistent data
    # volumes:
    #  - db-data:/data/db
    # OR
    #  - ./db-data:/data/db

  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    restart: always
    command: server /data
    ports:
     - 127.0.0.1:19000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
    # (!) Mount for persistent data
    # volumes:
    #  - s3-data:/data
    # OR
    #  - ./s3-data:/data

  # OLD (used with DSW 2, to be deleted after migration)
  mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - 127.0.0.1:27019:27017
    # (!) Mount for persistent data
    # volumes:
    #  - mongo-data:/data/db
    # OR (not working with Windows)
    #  - ./mongo:/data/db

  rabbitmq:
    image: rabbitmq:3.8.2-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

# volumes:
#   mongo-data:
#   db-data:
#   s3-data:
